version: '3'

# dbとwebサービスの立ち上げ
services:
  # dbはpostgresを使う
  db:
    platform: linux/x86_64  # M1 Macなどで必要
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code  # ソースコードを管理するフォルダ
      - .:/pip-lib  # ライブラリを管理するフォルダ
    environment:
      PYTHONUSERBASE: /pip-lib  # コンテナをbuildしなおさずにpip installでライブラリを更新できる
    ports:
      - "8000:8000"
    depends_on:
      - db  # dbを起動してからwebを起動する

  # pgadminを使う
  # https://chigusa-web.com/blog/django-docker-postgres/
  pgadmin4:
    image: dpage/pgadmin4
    ports:
        - 8888:80
    volumes:
        - pgadmin4_data:/var/lib/pgadmin
    environment:
        PGADMIN_DEFAULT_EMAIL: xxxxxxxxxx@gmail.com
        PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
        

volumes:
  postgres_data:
  pgadmin4_data: